version: '3.7'
services:
  db:
    image: mysql:5.7.30
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/minsola
      - ~/.ssh:/root/.ssh
      - log_data:/minsola/log
      - sockets:/minsola/tmp/sockets
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - public_data:/minsola/public
      - tmp_data:/minsola/tmp
      - sockets:/minsola/tmp/sockets
volumes:
  mysql_data:
  public_data:
  tmp_data:
  log_data:
  sockets: