version: '3.7'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development #production
    volumes:
      - .:/app_name
      - ~/.ssh:/root/.ssh
      - log_data:/minsola/log
  nginx:
    build:
      context: ./containers/nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - public_data:/minsola/public
      - tmp_data:/minsola/tmp
volumes:
  mysql_data:
  public_data:
  tmp_data:
  log_data: